language: php
node_js:
  - node

before_install:
  - npm install -g npm@latest

install:
  - npm -v
  - php prepare.php

script:
  - php test.php

after_script:
  - php report.php
  - php cleanup.php
